### PR TITLE
Full Rewrite - Merge or New Mod?

### PR DESCRIPTION
**Pull request by OverlordZorn**
Quite Frankly, this rework has become much more complex.

- A complete Restructure of the Mod
  - No scheduled code remaining
  - dependent on CBA
  - Vanilla Actions replaced with CBA's Context Menu
  - No more hard coded data, instead compatible items are defined through their config.
    -> Extensions, compats, new types of cigarettes etc are now much easier to ether add to the mod, or through extension mod with dependency.

- Includes Kneely's WW2 Cigarettes
- Includes Vespade's Immersive Crayons

- Has Compatibility for SOG:PF Cigarettes and Lighter

At the moment, all previous items have new classnames, there is no compat for them (yet).

There are 2 options:

A) Merge these changes into the original immersive cigarette mod.
- This will cause incompatibility with scenarios/mods using murshun functions.
- This will cause incompatibility with scenarios/mods using the previous murshun based items.
- Create a new Mod Dependency which was not present before (CBA).

B) Create a new Mod on the Workshop.
- People have to make the concious choise to switch over to the new mod.

@rebelvg

### CODE REVIEW

**Comment by rebelvg** [comment]
wow, this is huge, let me take a look.
I'd probably suggest doing it as a separate mod.
forcing CBA on people is probably not gonna fly.

**Comment by OverlordZorn** [comment]
> wow, this is huge, let me take a look. I'd probably suggest doing it as a separate mod. forcing CBA on people is probably not gonna fly.

Sounds good to me - i already created a workshop item (unlisted) for testing, so we can just use this if thats fine with you.

**Comment by rebelvg** [comment]
sure thing, not a problem.

**Comment by OverlordZorn** [comment]
https://github.com/OverlordZorn/immersion-cigs-rewrite

**Comment by OverlordZorn** [comment]
lmk if you have any questions btw, happy to elaborate

**Comment by rebelvg** [comment]
will do. love the github pipeline and hemtt integration. fantastic stuff.

**Pull request closed without merging**
